sudo: required

services:
  - docker

before_install:
  - docker build  -t aelkhalily/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aelkhalily/react-test npm test -- --coverage

after_script:
  - docker build -t aelkhalily/multi-client ./client
  - docker build -t aelkhalily/multi-nginx ./nginx
  - docker build -t aelkhalily/multi-server ./server
  - docker build -t aelkhalily/multi-worker ./worker
  #LOGIN TO DOCKER-HUB
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aelkhalily/multi-client
  - docker push aelkhalily/multi-nginx
  - docker push aelkhalily/multi-server
  - docker push aelkhalily/multi-worker
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted $ACCESS_KEY_ID"
  secret_access_key:
    secure: "Encrypted $SECRET_ACCESS_KEY"
  region: "us-east-2"
  app: "multi-docker"
  env: "multidocker-env"
  bucket_name: "https://s3.console.aws.amazon.com/s3/buckets/elasticbeanstalk-us-east-2-763967860641?region=us-east-2"
  bucket_path: "multi-docker"
  on:
    branch: main
  edge: true
