sudo: required
language: ruby
rvm:
  - 3
services:
  - docker
before_install:
  - docker build  -t aelkhalily/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aelkhalily/react-test npm test -- --coverage

after_script:
  - docker build -t aelkhalily/multi-client ./client
  - docker build -t aelkhalily/multi-nginx ./nginx
  - docker build -t aelkhalily/multi-server ./server
  - docker build -t aelkhalily/multi-worker ./worker
  #LOGIN TO DOCKER-HUB
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aelkhalily/multi-client
  - docker push aelkhalily/multi-nginx
  - docker push aelkhalily/multi-server
  - docker push aelkhalily/multi-worker
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-763967860641"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
