sudo: required
services:
  - docker

before_install:
  - docker build -t aelkhalily/test-react -f ./client/Dockerfile.dev
script:
  - docker run aelkhalily/test-react npm run test

after_success:
  - docker build -t aelkhalily/multi-client ./client
  - docker build -t aelkhalily/multi-nginx ./nginx
  - docker build -t aelkhalily/multi-server ./server
  - docker build -t aelkhalily/multi-worker ./worker

  #LOGIN TO DOCKER-HUB
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
